RushHour.App/Controllers/ApplicationController.cs
namespace RushHour.App.Controllers
{
    using System.Web.Hosting;
    using System.Web.Mvc;

    [Authorize(Roles = "Admin")]
    public class ApplicationController : Controller
    {
        public ActionResult Edit()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(string value)
        {
            string root = HostingEnvironment.MapPath("~/");

            System.IO.File.WriteAllText(root + "applicationSettings.txt", value);

            return RedirectToAction("Index", "Home");
        }
    }
}

RushHour.App/Controllers/AppointmentController.cs
namespace RushHour.App.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Hosting;
    using System.Web.Mvc;

    using AutoMapper;

    using Entities;

    using Microsoft.AspNet.Identity;

    using Models.BindingModels;
    using Models.ViewModels;

    using Services;

    [Authorize]
    public class AppointmentController : BaseController<Appointment, IAppointmentService>
    {
        public AppointmentController(IAppointmentService appointmentService)
            : base(appointmentService)
        {
        }
        
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var appointments = service.Get();

            if (!User.IsInRole("Admin"))
            {
                appointments = appointments
                    .Where(a => a.UserId == userId);
            }

            var appointmentModels = Mapper.Map<IEnumerable<Appointment>, IEnumerable<AppointmentViewModel>>(appointments);
            
            return View(appointmentModels);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(AppointmentBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            string userId = User.Identity.GetUserId();
            var appointment = new Appointment()
            {
                StartDateTime = model.StartDateTime,
                EndDateTime = model.EndDateTime,
                UserId = userId
            };

            if (service.Create(appointment, userId))
            {
                return RedirectToAction("Index");
            }
            else
            {
                int allowedAppointments = int.Parse(System.IO.File.ReadAllText(HostingEnvironment.MapPath("~/") + "applicationSettings.txt"));

                ModelState.AddModelError("", "There are already " + allowedAppointments + " parallel appointments");

                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;

            return View();
        }
        
        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(AppointmentBindingModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Id = id;

                return View();
            }

            var appointment = service.Get(id);

            appointment.StartDateTime = model.StartDateTime;
            appointment.EndDateTime = model.EndDateTime;
            service.Update(appointment);

            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int id)
        {
            var appointment = service.Get(id);

            service.Delete(appointment);

            return RedirectToAction("Index");
        }

        public ActionResult Cancel(int id)
        {
            var appointment = service.Get(id);

            service.Cancel(appointment);

            return RedirectToAction("Index");
        }
    }
}

RushHour.App/Controllers/UserController.cs
namespace RushHour.App.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;

    using AutoMapper;
    
    using Entities;

    using Microsoft.AspNet.Identity;

    using Models.BindingModels;
    using Models.ViewModels;

    using Services;

    [Authorize(Roles = "Admin")]
    public class UserController : BaseController<User, IService<User>>
    {
        public UserController(IService<User> userService)
            : base(userService)
        {
        }

        public ActionResult Index()
        {
            var users = service.Get();
            var userModels = Mapper.Map<IEnumerable<User>, IEnumerable<UserViewModel>>(users);

            return View(userModels);
        }

        public ActionResult Edit(string id)
        {
            ViewBag.Id = id;

            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(UserBindingModel model, string id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Id = id;

                return View();
            }

            var user = service.Get(id);

            user.UserName = model.Name;
            service.Update(user);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            var user = service.Get(id);

            service.Delete(user);

            return RedirectToAction("Index");
        }

        public new ActionResult Profile()
        {
            string userId = User.Identity.GetUserId();
            var user = service.Get(userId);
            var userModel = Mapper.Map<User, UserViewModel>(user);

            return View(userModel);
        }
    }
}

RushHour.App/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Rush Hour</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Rush hour", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Appointments", "Index", "Appointment")</li>
                    }

                    @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                    {
                        <li>@Html.ActionLink("Users", "Index", "User")</li>
                        <li>@Html.ActionLink("Edit Appointment Overlap", "Edit", "Application")</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Rush hour</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/datetime")
    @RenderSection("scripts", required: false)
</body>
</html>