RushHour.App/Models/ViewModels/ActivityViewModel.cs
namespace RushHour.App.Models.ViewModels
{
    public class ActivityViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public double Duration { get; set; }

        public decimal Price { get; set; }
    }
}

RushHour.App/Models/ViewModels/AppointmentViewModel.cs
namespace RushHour.App.Models.ViewModels
{
    using System;
    using System.Collections.Generic;

    public class AppointmentViewModel
    {
        public int Id { get; set; }

        public DateTime StartDateTime { get; set; }

        public DateTime EndDateTime { get; set; }

        public bool IsCancelled { get; set; }

        public string UserId { get; set; }

        public IEnumerable<ActivityViewModel> Activities { get; set; }
    }
}

RushHour.App/Models/ViewModels/UserViewModel.cs
namespace RushHour.App.Models.ViewModels
{
    public class UserViewModel
    {
        public string Id { get; set; }

        public string Name { get; set; }

        public string Phone { get; set; }
    }
}

RushHour.App/Controllers/ActivityController.cs
namespace RushHour.App.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;

    using Entities;
    
    using Models.BindingModels;

    using Services;

    [Authorize]
    public class ActivityController : BaseController<Activity, IService<Activity>>
    {
        public ActivityController(IService<Activity> activityService)
            : base(activityService)
        {
        }
        
        public ActionResult Create(int id)
        {
            ViewBag.AppointmentId = id;

            return View();
        }
        
        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(ActivityBindingModel model, int appointmentId)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.AppointmentId = appointmentId;

                return View();
            }

            var activity = new Activity()
            {
                Name = model.Name,
                Duration = model.Duration,
                Price = model.Price,
                AppointmentId = appointmentId
            };

            service.Create(activity);

            return RedirectToAction("Index", "Appointment");
        }
        
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;

            return View();
        }
        
        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(ActivityBindingModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Id = id;

                return View();
            }

            var activity = service.Get(id);

            activity.Name = model.Name;
            activity.Duration = model.Duration;
            activity.Price = model.Price;
            service.Update(activity);

            return RedirectToAction("Index", "Appointment");
        }
        
        public ActionResult Delete(int id)
        {
            var activity = service.Get(id);

            service.Delete(activity);

            return RedirectToAction("Index", "Appointment");
        }
    }
}

RushHour.App/Controllers/AppointmentController.cs
namespace RushHour.App.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Hosting;
    using System.Web.Mvc;

    using AutoMapper;

    using Entities;

    using Microsoft.AspNet.Identity;

    using Models.BindingModels;
    using Models.ViewModels;

    using Services;

    [Authorize]
    public class AppointmentController : BaseController<Appointment, IAppointmentService>
    {
        public AppointmentController(IAppointmentService appointmentService)
            : base(appointmentService)
        {
        }
        
        public ActionResult Index()
        {
            string userId = User.Identity.GetUserId();
            var appointments = service.Get();

            if (!User.IsInRole("Admin"))
            {
                appointments = appointments
                    .Where(a => a.UserId == userId);
            }

            var appointmentModels = Mapper.Map<IEnumerable<Appointment>, IEnumerable<AppointmentViewModel>>(appointments);
            
            return View(appointmentModels);
        }
        
        public ActionResult Create()
        {
            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public ActionResult Create(AppointmentBindingModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            string userId = User.Identity.GetUserId();
            var appointment = new Appointment()
            {
                StartDateTime = model.StartDateTime,
                EndDateTime = model.EndDateTime,
                UserId = userId
            };

            if (service.Create(appointment, userId))
            {
                return RedirectToAction("Index");
            }
            else
            {
                int allowedAppointments = int.Parse(System.IO.File.ReadAllText(HostingEnvironment.MapPath("~/") + "applicationSettings.txt"));

                ModelState.AddModelError("", "There are already " + allowedAppointments + " parallel appointments");

                return View();
            }
        }
        
        public ActionResult Edit(int id)
        {
            ViewBag.Id = id;

            return View();
        }
        
        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(AppointmentBindingModel model, int id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Id = id;

                return View();
            }

            var appointment = service.Get(id);

            appointment.StartDateTime = model.StartDateTime;
            appointment.EndDateTime = model.EndDateTime;
            service.Update(appointment);

            return RedirectToAction("Index");
        }
        
        public ActionResult Delete(int id)
        {
            var appointment = service.Get(id);

            service.Delete(appointment);

            return RedirectToAction("Index");
        }

        public ActionResult Cancel(int id)
        {
            var appointment = service.Get(id);

            service.Cancel(appointment);

            return RedirectToAction("Index");
        }
    }
}

RushHour.App/Controllers/UserController.cs
namespace RushHour.App.Controllers
{
    using System.Collections.Generic;
    using System.Web.Mvc;

    using AutoMapper;
    
    using Entities;

    using Microsoft.AspNet.Identity;

    using Models.BindingModels;
    using Models.ViewModels;

    using Services;

    [Authorize(Roles = "Admin")]
    public class UserController : BaseController<User, IService<User>>
    {
        public UserController(IService<User> userService)
            : base(userService)
        {
        }

        public ActionResult Index()
        {
            var users = service.Get();
            var userModels = Mapper.Map<IEnumerable<User>, IEnumerable<UserViewModel>>(users);

            return View(userModels);
        }

        public ActionResult Edit(string id)
        {
            ViewBag.Id = id;

            return View();
        }

        [ValidateAntiForgeryToken]
        [HttpPut]
        public ActionResult Edit(UserBindingModel model, string id)
        {
            if (!ModelState.IsValid)
            {
                ViewBag.Id = id;

                return View();
            }

            var user = service.Get(id);

            user.UserName = model.Name;
            service.Update(user);

            return RedirectToAction("Index");
        }

        public ActionResult Delete(string id)
        {
            var user = service.Get(id);

            service.Delete(user);

            return RedirectToAction("Index");
        }

        public new ActionResult Profile()
        {
            string userId = User.Identity.GetUserId();
            var user = service.Get(userId);
            var userModel = Mapper.Map<User, UserViewModel>(user);

            return View(userModel);
        }
    }
}

RushHour.App/Views/Shared/DisplayTemplates/ActivityViewModel.cshtml
@using RushHour.App.Models.ViewModels
@model ActivityViewModel

<div class="activity">
    <label>Name:</label>
    <span>@Model.Name</span>
    <br />
    <label>Duration:</label>
    <span>@Model.Duration minutes</span>
    <br />
    <label>Price:</label>
    <span>$@Model.Price</span>
    <hr />
    @Html.ActionLink("Edit", "Edit", "Activity", new { id = Model.Id }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Delete", "Delete", "Activity", new { id = Model.Id }, new { @class = "btn btn-danger" })
</div>

RushHour.App/Views/Shared/DisplayTemplates/AppointmentViewModel.cshtml
@using RushHour.App.Models.ViewModels
@using Microsoft.AspNet.Identity
@model AppointmentViewModel

<div class="appointment">
    <div>Starts: @Html.DisplayFor(m => m.StartDateTime)</div>
    <div>Ends: @Html.DisplayFor(m => m.EndDateTime)</div>
    @if (Model.IsCancelled)
    {
        <p>Cancelled</p>
    }
    <h3>Activities</h3>
    @if (Model.Activities.Count() == 0)
    {
        <p>No activities</p>
    }
    @Html.DisplayFor(m => m.Activities)
    @if (Model.Activities.Count() == 0)
    {
        @Html.ActionLink("Create Activity", "Create", "Activity", new { id = Model.Id }, new { @class = "btn btn-success" })
    }
    @if (Model.UserId == User.Identity.GetUserId())
    {
        <hr />
        @Html.ActionLink("Edit", "Edit", "Appointment", new { id = Model.Id }, new { @class = "btn btn-warning" })
        @Html.ActionLink("Delete", "Delete", "Appointment", new { id = Model.Id }, new { @class = "btn btn-danger" })
        @Html.ActionLink("Cancel", "Cancel", "Appointment", new { id = Model.Id }, new { @class = "btn btn-default" })
    }
</div>

RushHour.App/Views/Shared/DisplayTemplates/DateTime.cshtml
@model DateTime

@Model.Day/@Model.Month/@Model.Year @Model.TimeOfDay

RushHour.App/Views/Shared/DisplayTemplates/UserViewModel.cshtml
@using RushHour.App.Models.ViewModels
@model UserViewModel

<div class="user">
    @Model.Name
    @Html.ActionLink("Edit", "Edit", "User", new { id = Model.Id }, new { @class = "btn btn-warning" })
    @Html.ActionLink("Delete", "Delete", "User", new { id = Model.Id }, new { @class = "btn btn-danger" })
</div>